### ISSUE TITLE
Rotated Glyph Preview and mixed component glyphs

### ISSUE THREAD

**Issue by arialcrime** [jenskutilek/RoboFont#4]
Hey,

When Rotated Glyph Preview tries to display a glyph consisting of a component and an outline, the following traceback is thrown: 

> Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 131, in callObserver_withMethod_forEvent_withInfo_
  File "GlyphPreviewRotate.py", line 57, in _currentGlyphChangedObserver
  File "GlyphPreviewRotate.py", line 109, in _draw
  File "GlyphPreviewRotate.py", line 92, in _deepAppendGlyph
  File "/Applications/RoboFontPy3.app/Contents/Resources/lib/python3.6/fontParts/base/glyph.py", line 672, in appendGlyph
  File "/Applications/RoboFontPy3.app/Contents/Resources/lib/python3.6/fontParts/base/normalizers.py", line 830, in normalizeTransformationOffset
  File "/Applications/RoboFontPy3.app/Contents/Resources/lib/python3.6/fontParts/base/normalizers.py", line 692, in normalizeCoordinateTuple
fontParts.base.errors.FontPartsError: Coordinates must be tuple instances, not map.

Not sure if this is specific to the extension, or a general FontParts problem.

**Comment by frankrolf** [comment]
Should be fixed by #5.
